markdown:         rdiscount
pygments:         true
paginate:         6
plugins:    	 ./_plugins

title:            PIZn
url:              http://www.pizn.me
feed:             /atom.xml
author:
    name:         PIZn
    email:        pizner@gmail.com
    twitter:      twitter.com/piznlin
description:      "PIZn's another blog. Just to write down some note about work, such css, javascript and html."

copyright:
    - "Copyright &copy; 2011-2012 PIZn. All rights reserved."
    - Powered by <a href="http://jekyllrb.com" rel="nofollow" title="Jekyll">Jekyll</a>,Violet theme is a private theme, designed by <a href="http://www.pizn.net" rel="friend" title="pizn" target="_blank">PIZn</a>.
